### PR TITLE
seo, resolves #3

### LINKED ISSUE #3: SEO
The site has an average SEO core according to google webmaster tools.
Any suggestions would be appreciated!

### PR DESCRIPTION
**Pull request by sak-gg**
I added many new keywords in meta tags, and built a lot of outgoing links from your site to relevant popular sites. Hope it helps.

### CODE REVIEW

**Comment by abhinavagrawal1995** [comment]
This looks like a good start. Merged.

**Comment by sak-gg** [comment]
I didn't add links at HTML & CSS but now they look odd. Maybe you can add Wiki links on them. Or should I do it?

**Comment by abhinavagrawal1995** [comment]
Wiki links work. But if you're comfortable with css, could you maybe change the style to make them look the same irrespective of the anchor tag?

**Comment by sak-gg** [comment]
Yes I can do that with CSS but I think adding links would be a better and easier solution and it would ensure homogeneity of the links.

**Pull request merged**
